server:
  port: 8091


spring:
  cloud:
    gateway:
      routes:
      - id: overview_route
        uri: http://localhost:8085
        predicates:
          - Path=/tradegateway/overview
        filters:
          - SetPath=/tradeclient/overview/v1
          - name: CircuitBreaker
            args:
              name: overviewCircuitBreaker
              fallbackUri: forward:/overview-fallback
 
         